name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Snowflake CLI
        run: pip install snowflake-cli

      - name: Run SQL scripts
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          # Configure default connection (no name needed)
          snow connection add \
            --account $SNOWFLAKE_ACCOUNT \
            --username $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --role $SNOWFLAKE_ROLE \
            --database $SNOWFLAKE_DATABASE \
            --schema $SNOWFLAKE_SCHEMA \
            --warehouse $SNOWFLAKE_WAREHOUSE \
            --default \
            --no-interactive

          # Optional: list connections for debugging
          snow connection list

          # Run all SQL scripts in order using default connection
          for file in sql/*.sql; do
            echo "Running $file..."
            snow sql -f "$file"
          done




